BaseUrl= "https://vibhav19.github.io/magnetosphere/"
LanguageCode= "en-IN"
Title= "Earth's Magnetosphere"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2022"
canonifyurls = true

[author]
  name = "Vibhav Sinai Pissurlenkar"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "Our planet's natural shield for sustaining life on Earth"
  cover = "images/user.jpg"
  author = "Vibhav Sinai Pissurlenkar"
  authorlocation = ""
  #authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  #logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "VIBHAV19"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
